modLoader="javafml"
loaderVersion="[44,)"
license="GPLv3"
[[mods]]
modId="videoplayer"
version="2.5.3"
displayName="VideoPlayer"
authors="Goedix"
description='''
This mod allows the playback of videos in the user interface (GUI), you can play videos for all connected users or for a specific user.
'''
credits="Thanks J-RAP for the help with the API"
[[dependencies.videoplayer]]
modId="watermedia"
mandatory=true
versionRange="[0,)"
ordering="AFTER"
side="CLIENT"